CREATE TABLE product_images (
  id INT AUTO_INCREMENT PRIMARY KEY,
  filename VARCHAR(255) NOT NULL,
  file_path VARCHAR(500) NOT NULL,
  user_note TEXT DEFAULT NULL,
  tags JSON NOT NULL,
  description TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS demo_wallet (
  id INT UNSIGNED NOT NULL DEFAULT 1 PRIMARY KEY,
  balance INT UNSIGNED NOT NULL DEFAULT 5,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO demo_wallet (id, balance) VALUES (1, 5)
ON DUPLICATE KEY UPDATE id = id;
